//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string CodigoV { get; set; }
        public System.DateTime FechaYHoraSalida { get; set; }
        public System.DateTime FechaYHoraLlegada { get; set; }
        public string AeropuertoLlegada { get; set; }
        public string AeropuertoPartida { get; set; }
        public decimal Precio { get; set; }
        public int CantAsientos { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Aeropuerto Aeropuerto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
